Creation vie
Ndr6/Casse-Brique-ISN pull request #50
Opened 2017-04-26 15:47 UTC by DufDuf62

La réapparition de la balle fonctionne plutôt bien

2017-04-26 15:56 UTC, Ndr6 commented
Salut, tu dois résoudre les conflits pour que je valide

2017-04-26 17:18 UTC, Ndr6 requested changes
On ne peut pas bouger la raquette quand on perd une vie avant de relancer la raquette, il faut corriger ça avant de merge cette partie. Après il ne restera plus qu'a limiter le nombre de vies et à afficher un compteur de vies (c'est Benji qui s'en occupe ?)

2017-04-26 17:19 UTC, Ndr6 commented
En tout cas bravo, mis à part ça, ça fonctionne nickel :)

2017-04-27 19:03 UTC, Ndr6 reviewed
ça semble super :)
Tu as même changé des variables, merci
Je télécharge pour tester, puis j'approuve

2017-04-27 19:06 UTC, DufDuf62 commented
Logiquement tout fonctionne, j'ai même réglé d'autres petits problèmes

2017-04-27 19:09 UTC, Ndr6 commented
J'ai trouvé 2/3 bugs, mais rien qui empêche de merge : 
- Le logo pause n'apparait plus lors d'une pause normale
- Si on a un powerup en mourrant, le powerup se désactive 2 fois (son) : a la mort ET a la fin du délai

Mais en tout cas on a vraiment un truc jouable et agréable, c'est super

2017-04-27 19:10 UTC, Ndr6 commented
Mais le bug de la couleur des briques au démarrage est réglé, et ça c'est cool ^^

2017-04-27 19:10 UTC, Ndr6 commented
Donc, j'approuve les changements, tu peux appuyer sur le gros bouton vert ;)

2017-04-27 19:10 UTC, Ndr6 approved these changes

2017-04-27 19:11 UTC, Ndr6 commented
Une fois que tu as merge, tu peux cliquer sur le bouton pour supprimer la branche

2017-04-27 19:13 UTC, Ndr6 commented
Par contre j'ai rencontré un bug très bizarre à l'instant, j'ai tapé la balle avec exactement le coin de la raquette (je crois) et elle est passée à travers, c'est peut être lié au bug dont parlait Mr Sautière ?

2017-04-27 19:22 UTC, DufDuf62 commented
Oui ce bug arrive très rarement et je pense savoir pourquoi mais c'est assez compliqué de le régler et oui je pense que c'est le but de Mr.Sautiere

2017-04-27 19:25 UTC, merged